### ISSUE TITLE
Sound output is not the same as trackmania sound output

### ISSUE THREAD

**Issue by Dryhb** [MisfitMaid/tm-bonk#12]
For example trackmania can do the sounds (car, engine, surface ...) on a speaker while the bonk plays in headphones (also connected) but not selected in the sound section of trackmania settings.
Ig align with the trackmania settings if possible

**Comment by sylae** [comment]
Unfortunately, all audio device configuration is handled by Openplanet itself, and no APIs are provided for changing that to a different audio device at the plugin level.

You can set openplanet sounds to play via the proper device by going to `F3 -> Openplanet -> Settings -> Audio`. There you should have sound options as well as a way to pick a different audio output.
