### ISSUE TITLE
No bonk sound

### ISSUE THREAD

**Issue by XertroV** [MisfitMaid/tm-bonk#4]
AR_Down tried bonk today on-stream and the red outline showed up but there was no bonk sound (volume at 0.4 and then 1.0, same result). Down mentioned that the AFK queue alert sound worked. 

About 20 minutes in: https://www.twitch.tv/videos/1750320462

**Comment by sylae** [comment]
interesting, no clue why it's doing that, it should be called at the same time as the flash. I wonder if it's something with the audio sample not being loaded? idk

**Comment by sylae** [comment]
version using wav instead of mp3 didn't fix it

**Comment by sylae** [comment]
Without being able to replicate this I'm not sure what I'm able to do, gonna leave this open for a bit in case there's ideas but yeah.

My guess is some weird system thing? Idk

**Comment by sylae** [comment]
cannot reproduce ig
